services:
  next:
    build: .
    command: pnpm dev --port 3000
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - next_node_modules:/app/node_modules
      - next_build:/app/.next
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - NEXT_PRIVATE_DEV_SERVER_PACKAGE=webpack

  vercel:
    build: .
    command: vercel dev --listen 3001 --token=${VERCEL_TOKEN}
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - vercel_node_modules:/app/node_modules
      - vercel_build:/app/.next
    environment:
      - NODE_ENV=development
      - VERCEL_TOKEN=${VERCEL_TOKEN}

volumes:
  next_node_modules:
  next_build:
  vercel_node_modules:
  vercel_build: