openapi: 3.1.0
info:
  title: Hello API
  version: "1.0.0"
  description: Simple Hello API with parameter validation and structured error response.

servers:
  - url: /

paths:
  /api/hello:
    get:
      summary: Returns a hello message
      operationId: GetApiHello
      parameters:
        - name: content
          in: query
          required: true
          schema:
            type: string
            minLength: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message