openapi: 3.1.0
info:
  title: GitHub Stats API
  version: "1.0.0"
  description: Provides statistics across GitHub repositories.

servers:
  - url: /api/v1

paths:
  /status:
    get:
      summary: Check API Status
      operationId: GetApiStatus
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
components:
  schemas:
    StatusResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message