openapi: 3.1.0
info:
  title: GitHub Stats API
  version: "1.0.0"
  description: Provides statistics across GitHub repositories.

servers:
  - url: /api/v1

paths:
  /status:
    get:
      summary: Check API Status
      operationId: GetApiStatus
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'


  /user:
    get:
      summary: Get User Information
      operationId: GetUserInfo
      parameters:
        - name: access_token
          in: query
          required: true
          schema:
            type: string
            description: access_token for authentication
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /contribution-days:
    get:
      summary: Get Contribution Days
      operationId: GetContributionDays
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          schema:
            type: string
            description: access_token for authentication
      responses:
        '200':
          description: Contributions retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContributionDaysResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /language-stats:
    get:
      summary: Get Language Statistics
      operationId: GetLanguageStats
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          schema:
            type: string
            description: access_token for authentication
      responses:
        '200':
          description: Language statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageStatsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    StatusResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    UserResponse:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        avatar_url:
          type: string
          format: uri
      
    ContributionDay:
      type: object
      properties:
        date:
          type: string
          format: date
        count:
          type: integer
      required:
        - date
        - count

    ContributionDaysResponse:
      type: object
      properties:
        username:
          type: string
        total:
          type: integer
        days:
          type: array
          items:
            $ref: '#/components/schemas/ContributionDay'
      required:
        - username
        - days
        - total

    LanguageStats:
      type: object
      properties:
        language:
          type: string
        lines:
          type: integer
        color:
          type: string
          description: GitHub language color in hex format
      required:
        - language
        - lines
        - color

    RepositoryLanguageStats:
      type: object
      properties:
        repository:
          type: string
        languages:
          type: array
          items:
            $ref: '#/components/schemas/LanguageStats'
      required:
        - repository
        - languages

    LanguageStatsResponse:
      type: object
      properties:
        username:
          type: string
        total_languages:
          type: array
          items:
            $ref: '#/components/schemas/LanguageStats'
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/RepositoryLanguageStats'
      required:
        - username
        - total_languages
        - repositories

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message