name: Format

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  biome:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run format check
        run: |
          if ! pnpm biome check .; then
            echo "❌ Biome formatting issues found. Please run 'pnpm biome check --apply .' to fix them."
            exit 1
          fi
          echo "✅ All files are properly formatted with Biome."

  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Run format check
        run: |
          # Check if any files need formatting
          UNFORMATTED=$(find ./api -name "*.go" -exec gofmt -l {} \; 2>/dev/null || true)
          if [ -n "$UNFORMATTED" ]; then
            echo "❌ Go formatting issues found in the following files:"
            echo "$UNFORMATTED"
            echo "Please run 'gofmt -w \$(find ./api -name \"*.go\")' to fix them."
            exit 1
          fi
          echo "✅ All Go files are properly formatted."